version: "3"
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE='envoy'
      - MYSQL_USER='clint'
      - MYSQL_PASSWORD='0227'
      - MYSQL__ROOT_PASSWORD='0227'
      - MYSQL_HOST='192.168.1.15'
    volumes:
      - /tmp/app/mysqld:/run/mysqld
      - ./db:/var/lib/mysql
    ports:
      - "8279:8279"
  envoy:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/envoy
    command: python envoy/manage.py runserver 192.168.1.15:8000
    depends_on:
      - db
